apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: docker-registry
spec:
  type: NodePort
  ports:
    - port: 8000         # Internal port of the FastAPI app
      targetPort: 8000    # The container port the app is running on
      nodePort: 32001     # External NodePort (can be omitted for auto-assignment)
  selector:
    app: customer-service
