apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: localhost:32000/postgres:17rc1  # Your private Docker registry image
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "customeruser"  # Customize this value
        - name: POSTGRES_PASSWORD
          value: "password"  # Customize this value
        - name: POSTGRES_DB
          value: "customerdb"  # Customize the database name
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data  # Mount the PVC for persistent storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: docker-registry
spec:
  ports:
    - port: 5432  # PostgreSQL port
      targetPort: 5432
  selector:
    app: postgres
  clusterIP: None  # Headless service for internal communication
