apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: docker-registry
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi  # Adjust size as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres"  # Path on your Kubernetes node for data storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: docker-registry
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Match with the PersistentVolume
