apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: docker-registry
spec:
  type: NodePort
  ports:
    - port: 5000        # Internal port of the Docker registry
      targetPort: 5000   # Container port
      nodePort: 32000    # External NodePort (can be auto-assigned if omitted)
  selector:
    app: docker-registry
