apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.postgresPort }}
      targetPort: {{ .Values.service.postgresPort }}
      nodePort: {{ .Values.service.postgresNodePort }}
  selector:
    app: postgres
